# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-03 07:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20191003_0618'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set([('user', 'title')]),
        ),
    ]
