# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-03 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191003_0708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('-created_at',)},
        ),
    ]
