# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-04 00:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userextrainfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userextrainfo',
            old_name='avatar',
            new_name='avatar_email',
        ),
    ]
