# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-04 05:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191004_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextrainfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_extra', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
